### PR TITLE
more output from ns_analyse, in particular Helmholtz free energy

### PR DESCRIPTION
**Pull request by bernstei**
Output Helmholtz free energy, assuming that entropy is 0 at last iteration (which is only an approximation, but one that improves as number of iterations -> infinity), so F(T=0) = U(T=0) + PV(T=0).

Also pprint ns_args and movement_args to be more readable and avoid upsetting mpirun implementations that can't handle very long lines.

### CODE REVIEW

**Comment by liviabp** [comment]
Thanks, happy with the changes! One thing, U+pV is the enthalpy, you'd leave that unchanged, and add the Helmholtz energy F=U-TS, as an extra column?

**Comment by bernstei** [comment]
On Feb 23, 2021, at 9:32 AM, liviabp <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks, happy with the changes! One thing, U+pV is the enthalpy, you'd leave that unchanged, and add the Helmholtz energy F=U-TS, as an extra column?

I'm not sure what you mean here. My intent was just to add the Helmholtz free energy, and not change anything else.

Noam

**Comment by bernstei** [comment]
@liviabp can you explain your last comment?

**Comment by liviabp** [comment]
Sorry, @noambernstein, not sure where my previous reply disappeared... I only got confused by your original comment, you said "Helmholtz free energy [...] so F(T=0) = U(T=0) + PV(T=0)", but U+PV is enthalpy (H), not the the Helmholtz free energy (F), so I thought you were talking about changing two things.

**Comment by bernstei** [comment]
> Sorry, @noambernstein, not sure where my previous reply disappeared... I only got confused by your original comment, you said "Helmholtz free energy [...] so F(T=0) = U(T=0) + PV(T=0)", but U+PV is enthalpy (H), not the the Helmholtz free energy (F), so I thought you were talking about changing two things.

No, I just meant that I'm assuming that at T=0 F = U + PV (i.e. S = 0), to fix the offset between them.

**Pull request merged**
